apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oisp-sensor

resources:
  - namespace.yaml
  - configmap.yaml
  - daemonset.yaml
  # Uncomment to deploy test app:
  # - test-app.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: oisp
